---

- name: Run Docker Compose 
#  hosts: localhost
  hosts: webservers
  become: yes

  tasks:

    - name: Install Docker.
      package:
        name: docker.io
        state: present

    - name: Install Docker SDK for Python.
      pip:
        name: docker
        state: present

    - name: Check current docker-compose version
      command: docker-compose --version
      register: docker_compose_vsn
      changed_when: false
      failed_when: false
      check_mode: no

    - community.docker.docker_compose:
        project_src: .
        state: absent

    - name: Create and Start services
      community.docker.docker_compose:
        project_src: .
        build: yes

    # - name: Check current docker-compose version
    #   command: docker-compose --version
    #   register: docker_compose_vsn
    #   changed_when: false
    #   failed_when: false
    #   check_mode: no

    # - set_fact:
    #     docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
    #   when:
    #     - docker_compose_vsn.stdout is defined

    # - name: Install docker-compose
    #   get_url: 
    #     url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    #     dest: /usr/local/bin/docker-compose
    #     mode: 'u+x,g+x'